language: ruby

env:
  global:
    - secure: "Bn4TImn1xVcjFTxGHuRMvXyQBck5Wya0Q8Mae9xTMdPUSBdCNxYqBSXkfuj1\n4E00jpdysNDqTVOXe8SwhF5vZKQN/1Iy1NPvGCr+aD/0X4IDbTz8x7rNQ8Rk\n83mdni54yrjC8s2UPpuci4hdLUX9UMAa2SOy7R7hH4jg1/AafcQ="

after_script:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install https://github.com/ddollar/heroku-anvil
  - heroku build -r ancient-temple-7190  -b https://github.com/heroku/heroku-buildpack-ruby.git
  - heroku run rake db:migrate --app ancient-temple-7190
